name: Canlı Ubuntu Terminali
on: [push]

jobs:
  canli-baglanti:
    runs-on: ubuntu-22.04
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Canlı Terminal Sunucusunu Başlat
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
